### ISSUE TITLE
extract_features() method

### ISSUE THREAD

**Issue by edosyhptra** [habla-liaa/ser-with-w2v2#15]
Where did u get extract_features() (line 155 in tasks/features_extractors.py) method from?

Im trying to implement your code on my own. However, Im getting this kind of error:
`AttributeError: 'Wav2Vec2Embedding' object has no attribute 'extract_features'`

The error occured when I call extract_features() method:
`activations = self.model.extract_features(wav, None)`

**Comment by mrpep** [comment]
I made a fork of fairseq and added some methods to the original model to extract the activations. See here: https://github.com/mrpep/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py#L633

**Comment by edosyhptra** [comment]
Ive forked fairseq from yours and cloned it locally on my own. But I still get the same error when I run the script.

Did I miss something?

**Comment by edosyhptra** [comment]
btw, whats the different with features_extractor() or feature_aggregator() in the wav2vec_featurize original file?

**Comment by edosyhptra** [comment]
turns out I got something wrong in my code. But, it works!.

Thanks a lot @mrpep !
