### ISSUE TITLE
Warning: Cannot resolve tags ['Ravdess_max_audio_size']

### ISSUE THREAD

**Issue by jiminbot20** [habla-liaa/ser-with-w2v2#7]
https://github.com/habla-liaa/ser-with-w2v2/blob/c9be8a9bc8c6c6969838e3e77c2fc8af10e27136/configs/datasets/ravdess.yaml#L1

when running shell file this warning occurs.

![image](https://user-images.githubusercontent.com/63258184/135716933-ca393ed5-1b1a-4a44-8ede-6b7d8a5c1f2f.png)

so 'Ravdess_max_audio_size' this variable needs to announce, I guess. 
unlikely to this code, in ser-with-w2v2/configs/datasets/iemocap_impro.yaml, 'IEMOCAP_max_audio_size' is written

https://github.com/habla-liaa/ser-with-w2v2/blob/c9be8a9bc8c6c6969838e3e77c2fc8af10e27136/configs/datasets/iemocap_impro.yaml#L10

**Comment by mrpep** [comment]
In the case of RAVDESS it is not needed to truncate the audios because the longest one is 6 seconds long, which is a lot less than 240k samples. In the other hand, some IEMOCAP audios are longer than 15 seconds (which corresponds to 240k samples).
